# Generated by Django 6.0.5 on 2026-09-29 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("employees", "0017_customreport"),
    ]

    operations = [
        migrations.CreateModel(
            name="Asset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("asset_tag", models.CharField(db_index=True, max_length=50, unique=True)),
                ("category", models.CharField(default="laptop", max_length=50)),
                ("brand", models.CharField(blank=True, default="", max_length=100)),
                ("serial", models.CharField(blank=True, default="", max_length=100)),
                ("processor", models.CharField(blank=True, default="", max_length=100)),
                ("ram", models.CharField(blank=True, default="", max_length=100)),
                ("date_of_allotment", models.DateField(blank=True, null=True)),
                ("date_of_recover", models.DateField(blank=True, null=True)),
                ("has_bag", models.BooleanField(default=False)),
                ("previously_used", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assets",
                        to="employees.employee",
                    ),
                ),
            ],
            options={
                "ordering": ["asset_tag"],
                "indexes": [
                    models.Index(fields=["assigned_to"], name="assets_asse_assigne_8034d6_idx")
                ],
            },
        ),
    ]
