# Generated by Django 5.1.15 on 2026-09-29 09:47

import django.db.models.deletion
import lms_integration.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0011_seed_org_masters'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(default=lms_integration.models.new_event_id, max_length=80, unique=True)),
                ('event_type', models.CharField(max_length=50)),
                ('schema_version', models.CharField(default='1.0', max_length=10)),
                ('direction', models.CharField(choices=[('outbound', 'HRMS → LMS'), ('inbound', 'LMS → HRMS')], max_length=10)),
                ('source', models.CharField(max_length=20)),
                ('correlation_id', models.CharField(default=lms_integration.models.new_correlation_id, max_length=80)),
                ('payload', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('SUCCEEDED', 'Succeeded'), ('RETRYING', 'Retrying'), ('FAILED', 'Failed'), ('RECONCILED', 'Reconciled')], default='PENDING', max_length=12)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('next_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('occurred_at', models.DateTimeField()),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lms_events', to='employees.employee')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='IntegrationDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.CharField(max_length=300)),
                ('attempt_no', models.PositiveIntegerField()),
                ('succeeded', models.BooleanField(default=False)),
                ('http_status', models.PositiveIntegerField(blank=True, null=True)),
                ('error', models.TextField(blank=True)),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('attempted_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='lms_integration.integrationevent')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='LearningEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_event_id', models.CharField(blank=True, max_length=80)),
                ('source_occurred_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course_id', models.CharField(max_length=64)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('category', models.CharField(blank=True, max_length=120)),
                ('path_id', models.CharField(blank=True, max_length=64)),
                ('path_name', models.CharField(blank=True, max_length=255)),
                ('mandatory', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('assigned', 'Assigned'), ('in_progress', 'In progress'), ('completed', 'Completed')], default='assigned', max_length=20)),
                ('progress', models.PositiveSmallIntegerField(default=0)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='employees.employee')),
            ],
            options={
                'ordering': ['employee_id', '-assigned_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='LmsIdentityLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('learner_id', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending provisioning'), ('linked', 'Linked'), ('deactivated', 'Deactivated'), ('conflict', 'Conflict — needs resolution')], default='pending', max_length=20)),
                ('linked_at', models.DateTimeField(blank=True, null=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lms_link', to='employees.employee')),
            ],
            options={
                'ordering': ['employee_id'],
            },
        ),
        migrations.CreateModel(
            name='ReconciliationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger', models.CharField(default='manual', max_length=20)),
                ('status', models.CharField(default='running', max_length=20)),
                ('provision', models.BooleanField(default=False)),
                ('summary', models.JSONField(blank=True, default=dict)),
                ('findings', models.JSONField(blank=True, default=list)),
                ('error', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('started_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_event_id', models.CharField(blank=True, max_length=80)),
                ('source_occurred_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessment_id', models.CharField(max_length=64)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('course_id', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(blank=True, max_length=30)),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('max_score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='employees.employee')),
            ],
            options={
                'ordering': ['employee_id', '-completed_at', 'id'],
                'constraints': [models.UniqueConstraint(fields=('employee', 'assessment_id'), name='lms_assessment_unique')],
            },
        ),
        migrations.CreateModel(
            name='EmployeeCertification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_event_id', models.CharField(blank=True, max_length=80)),
                ('source_occurred_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('certification_id', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=255)),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expiring', 'Expiring soon'), ('expired', 'Expired'), ('revoked', 'Revoked')], default='active', max_length=20)),
                ('credential_url', models.URLField(blank=True, max_length=500)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='employees.employee')),
            ],
            options={
                'ordering': ['employee_id', 'expires_at', 'id'],
                'constraints': [models.UniqueConstraint(fields=('employee', 'certification_id'), name='lms_certification_unique')],
            },
        ),
        migrations.CreateModel(
            name='EmployeeSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_event_id', models.CharField(blank=True, max_length=80)),
                ('source_occurred_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('skill_id', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=255)),
                ('proficiency', models.CharField(blank=True, max_length=40)),
                ('proficiency_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('evidence_refs', models.JSONField(blank=True, default=list)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='employees.employee')),
            ],
            options={
                'ordering': ['employee_id', 'name'],
                'constraints': [models.UniqueConstraint(fields=('employee', 'skill_id'), name='lms_skill_unique')],
            },
        ),
        migrations.AddIndex(
            model_name='integrationevent',
            index=models.Index(fields=['direction', 'status', 'next_attempt_at'], name='lms_integra_directi_7de26d_idx'),
        ),
        migrations.AddIndex(
            model_name='integrationevent',
            index=models.Index(fields=['employee', 'direction', 'status'], name='lms_integra_employe_29ef3e_idx'),
        ),
        migrations.AddIndex(
            model_name='integrationevent',
            index=models.Index(fields=['event_type'], name='lms_integra_event_t_3a0f8a_idx'),
        ),
        migrations.AddConstraint(
            model_name='learningenrollment',
            constraint=models.UniqueConstraint(fields=('employee', 'course_id'), name='lms_enrollment_unique'),
        ),
    ]
