# Generated by Django 5.1.15 on 2026-10-01 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0002_comp_off_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compoffrequest',
            name='leave_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='comp_off_requests', to='leave.leavetype'),
        ),
    ]
