# Generated by Django 5.1.15 on 2026-09-25 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
        ('employees', '0004_org_structure_and_lifecycle'),
    ]

    operations = [
        migrations.CreateModel(
            name='PolicySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regularisation_grace_days', models.PositiveIntegerField(default=3)),
                ('absconding_threshold_days', models.PositiveIntegerField(default=5)),
                ('no_attendance_enabled', models.BooleanField(default=True)),
                ('no_attendance_leave_days_deducted', models.DecimalField(decimal_places=1, default=1, max_digits=4)),
                ('late_arrival_enabled', models.BooleanField(default=False)),
                ('late_arrival_leave_days_deducted', models.DecimalField(decimal_places=1, default=0.5, max_digits=4)),
                ('late_arrival_threshold_count', models.PositiveIntegerField(default=3)),
                ('early_leaving_enabled', models.BooleanField(default=False)),
                ('early_leaving_leave_days_deducted', models.DecimalField(decimal_places=1, default=0.5, max_digits=4)),
                ('early_leaving_threshold_count', models.PositiveIntegerField(default=3)),
                ('work_hours_enabled', models.BooleanField(default=False)),
                ('work_hours_leave_days_deducted', models.DecimalField(decimal_places=1, default=0.5, max_digits=4)),
                ('work_hours_min_work_hours', models.DecimalField(decimal_places=1, default=8, max_digits=4)),
                ('comp_off_accrual_enabled', models.BooleanField(default=True)),
                ('comp_off_accrual_overtime_hours_per_comp_off', models.DecimalField(decimal_places=1, default=8, max_digits=5)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('break_minutes', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employees', models.ManyToManyField(blank=True, related_name='shifts', to='employees.employee')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
