# Generated by Django 5.1.15 on 2026-09-28 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_policysettings_shift'),
        ('employees', '0004_org_structure_and_lifecycle'),
    ]

    operations = [
        migrations.CreateModel(
            name='PenalisationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('absent_date', models.DateField()),
                ('regularisation_deadline', models.DateField()),
                ('days_overdue', models.PositiveIntegerField()),
                ('reason', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('applied', 'Applied'), ('overturned', 'Overturned')], default='applied', max_length=20)),
                ('overturned_reason', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penalisation_records', to='employees.employee')),
                ('overturned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='employees.employee')),
            ],
            options={
                'ordering': ['-absent_date'],
                'constraints': [models.UniqueConstraint(fields=('employee', 'absent_date'), name='unique_penalisation_per_employee_day')],
            },
        ),
    ]
