# Generated by Django 5.1.15 on 2026-09-28 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_penalisationrecord'),
        ('leave', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='penalisationrecord',
            name='leave_balance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='penalisations', to='leave.leavebalance'),
        ),
        migrations.AddField(
            model_name='penalisationrecord',
            name='leave_days_deducted',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4),
        ),
        migrations.AddField(
            model_name='policysettings',
            name='penalty_leave_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='leave.leavetype'),
        ),
    ]
