# Generated by Django 5.1.15 on 2026-09-28 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0004_penalisationrecord_leave_balance_and_more"),
        ("employees", "0004_org_structure_and_lifecycle"),
        ("leave", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="policysettings",
            name="comp_off_leave_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="leave.leavetype",
            ),
        ),
        migrations.CreateModel(
            name="CompOffAccrualState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("uncredited_overtime_minutes", models.PositiveIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "employee",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comp_off_accrual_state",
                        to="employees.employee",
                    ),
                ),
            ],
        ),
    ]
