# Generated by Django 5.1.15 on 2026-10-01 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_policysettings_comp_off_leave_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='policysettings',
            name='comp_off_accrual_enabled',
        ),
        migrations.RemoveField(
            model_name='policysettings',
            name='comp_off_accrual_overtime_hours_per_comp_off',
        ),
        migrations.DeleteModel(
            name='CompOffAccrualState',
        ),
    ]
