# Generated by Django 5.1.15 on 2026-10-01 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_remove_comp_off_accrual'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='policysettings',
            name='comp_off_leave_type',
        ),
    ]
