# Generated by Django 5.1.15 on 2026-09-28 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0008_task_assignee_and_access_grants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onboardingaccessgrant',
            name='area',
            field=models.CharField(choices=[('bank_details', 'Bank details'), ('identity_documents', 'Identity documents'), ('education', 'Degrees & certificates'), ('laptop', 'Issue laptop'), ('work_email', 'Work email setup'), ('id_card', 'Issue ID card')], max_length=30),
        ),
        migrations.AlterField(
            model_name='onboardingtask',
            name='owner',
            field=models.CharField(choices=[('new_hire', 'New hire'), ('hr_admin', 'HR Admin'), ('manager', 'Manager'), ('buddy', 'Buddy'), ('it_admin', 'IT Admin')], default='new_hire', max_length=20),
        ),
        migrations.AlterField(
            model_name='onboardingtasktemplate',
            name='owner',
            field=models.CharField(choices=[('new_hire', 'New hire'), ('hr_admin', 'HR Admin'), ('manager', 'Manager'), ('buddy', 'Buddy'), ('it_admin', 'IT Admin')], default='new_hire', max_length=20),
        ),
    ]
