# Generated by Django 5.1.15 on 2026-09-29 08:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("employees", "0004_org_structure_and_lifecycle"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("subject", models.CharField(max_length=255)),
                ("description", models.TextField(max_length=5000)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("IT & Access", "IT & Access"),
                            ("Facilities", "Facilities"),
                            ("Food", "Food"),
                            ("Cab", "Cab"),
                            ("Finance & Admin", "Finance & Admin"),
                            ("Others", "Others"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[("Low", "Low"), ("Medium", "Medium"), ("High", "High")],
                        default="Medium",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("New", "New"),
                            ("In progress", "In progress"),
                            ("Waiting", "Waiting"),
                            ("Resolved", "Resolved"),
                            ("Closed", "Closed"),
                            ("Reopened", "Reopened"),
                        ],
                        default="New",
                        max_length=20,
                    ),
                ),
                ("admin_comment", models.TextField(blank=True)),
                ("reopen_count", models.PositiveIntegerField(default=0)),
                ("escalation_level", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_help_tickets",
                        to="employees.employee",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="help_tickets",
                        to="employees.employee",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TicketActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("status-updated", "Status updated"),
                            ("reopened", "Reopened"),
                            ("edited", "Edited"),
                            ("assigned", "Assigned"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "previous_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("New", "New"),
                            ("In progress", "In progress"),
                            ("Waiting", "Waiting"),
                            ("Resolved", "Resolved"),
                            ("Closed", "Closed"),
                            ("Reopened", "Reopened"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "new_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("New", "New"),
                            ("In progress", "In progress"),
                            ("Waiting", "Waiting"),
                            ("Resolved", "Resolved"),
                            ("Closed", "Closed"),
                            ("Reopened", "Reopened"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("comment", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="help.ticket",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
    ]
