# Generated by Django 5.1.15 on 2026-09-29 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("help", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="category",
            field=models.CharField(
                choices=[
                    ("IT & Access", "IT & Access"),
                    ("Facilities", "Facilities"),
                    ("Food", "Food"),
                    ("Cab", "Cab"),
                    ("Finance & Admin", "Finance & Admin"),
                    ("HR", "HR"),
                    ("Others", "Others"),
                ],
                max_length=32,
            ),
        ),
    ]
