# Generated by Django 5.1.15 on 2026-09-29 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0004_org_structure_and_lifecycle"),
        ("help", "0002_alter_ticket_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="CategoryAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("IT & Access", "IT & Access"),
                            ("Facilities", "Facilities"),
                            ("Food", "Food"),
                            ("Cab", "Cab"),
                            ("Finance & Admin", "Finance & Admin"),
                            ("HR", "HR"),
                            ("Others", "Others"),
                        ],
                        max_length=32,
                        unique=True,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assignee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="help_category_assignments",
                        to="employees.employee",
                    ),
                ),
            ],
            options={
                "ordering": ["category"],
            },
        ),
    ]
