# Generated by Django 5.1.15 on 2026-09-30 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0013_employee_about_skills'),
        ('help', '0003_categoryassignment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoryassignment',
            options={'ordering': ['category', 'id']},
        ),
        migrations.AlterField(
            model_name='categoryassignment',
            name='category',
            field=models.CharField(choices=[('IT & Access', 'IT & Access'), ('Facilities', 'Facilities'), ('Food', 'Food'), ('Cab', 'Cab'), ('Finance & Admin', 'Finance & Admin'), ('HR', 'HR'), ('Others', 'Others')], max_length=32),
        ),
        migrations.AddConstraint(
            model_name='categoryassignment',
            constraint=models.UniqueConstraint(fields=('category', 'assignee'), name='unique_help_owner_per_category'),
        ),
    ]
