# Generated by Django 6.0.5 on 2026-09-29 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0006_ensure_columns_on_fresh_db"),
        ("employees", "0017_customreport"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="acknowledgement_required",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="document",
            name="audience",
            field=models.CharField(
                choices=[
                    ("hr_only", "HR only"),
                    ("hr_and_manager", "HR + Manager"),
                    ("employee", "Employee (owner only)"),
                    ("all_employees", "All employees"),
                ],
                default="all_employees",
                max_length=32,
            ),
        ),
        migrations.CreateModel(
            name="DocumentAcknowledgement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("acknowledged_at", models.DateTimeField(auto_now_add=True)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="acknowledgements",
                        to="documents.document",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_acknowledgements",
                        to="employees.employee",
                    ),
                ),
            ],
            options={
                "ordering": ["-acknowledged_at"],
                "indexes": [
                    models.Index(
                        fields=["document", "employee"], name="documents_d_documen_f16194_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("document", "employee"), name="unique_document_acknowledgement"
                    )
                ],
            },
        ),
    ]
