# Generated by Django 6.0.5 on 2026-09-30 07:46

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0014_user_roles_m2m"),
        ("documents", "0009_document_rejection_reason_and_more"),
    ]

    operations = [
        # State-only: the Document primary key is a uuid (0001, 0004, 0012). The
        # sibling 0007_document_pk_bigint branch declares it bigint in migration
        # state, and whether that has already run when this migration does depends
        # on the history of the database (a fresh one runs it later; an upgraded or
        # rolled-back-and-replayed one has it applied already). Without this, the
        # foreign key below was built as bigint against the real uuid column in the
        # second case and Postgres refused it. Declaring the real type here makes
        # the result independent of that history. No database change: the column
        # already is a uuid.
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name="document",
                    name="id",
                    field=models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                )
            ],
            database_operations=[],
        ),
        migrations.CreateModel(
            name="DocumentAudienceRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("acknowledge_required", models.BooleanField(default=False)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audience_roles",
                        to="documents.document",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="accounts.role",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["document", "role"], name="documents_d_documen_d4f428_idx")
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("document", "role"), name="unique_document_audience_role"
                    )
                ],
            },
        ),
    ]
