# Generated by Django 6.0.5 on 2026-09-30 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0014_user_roles_m2m"),
        ("documents", "0009_document_rejection_reason_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentAudienceRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("acknowledge_required", models.BooleanField(default=False)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audience_roles",
                        to="documents.document",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="accounts.role",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["document", "role"], name="documents_d_documen_d4f428_idx")
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("document", "role"), name="unique_document_audience_role"
                    )
                ],
            },
        ),
    ]
