# Generated by Django 5.1.15 on 2026-09-29 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0011_seed_org_masters'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('relationship', models.CharField(max_length=60)),
                ('phone', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_contacts', to='employees.employee')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_line1', models.CharField(blank=True, default='', max_length=200)),
                ('current_line2', models.CharField(blank=True, default='', max_length=200)),
                ('current_city', models.CharField(blank=True, default='', max_length=100)),
                ('current_state', models.CharField(blank=True, default='', max_length=100)),
                ('current_postal_code', models.CharField(blank=True, default='', max_length=12)),
                ('current_country', models.CharField(blank=True, default='India', max_length=100)),
                ('permanent_same_as_current', models.BooleanField(default=True)),
                ('permanent_line1', models.CharField(blank=True, default='', max_length=200)),
                ('permanent_line2', models.CharField(blank=True, default='', max_length=200)),
                ('permanent_city', models.CharField(blank=True, default='', max_length=100)),
                ('permanent_state', models.CharField(blank=True, default='', max_length=100)),
                ('permanent_postal_code', models.CharField(blank=True, default='', max_length=12)),
                ('permanent_country', models.CharField(blank=True, default='', max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='employees.employee')),
            ],
        ),
    ]
