# Generated by Django 6.0.5 on 2026-09-29 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0011_seed_org_masters"),
    ]

    operations = [
        migrations.AddField(
            model_name="businessunit",
            name="code",
            field=models.CharField(blank=True, db_index=True, default="", max_length=30),
        ),
        migrations.AddField(
            model_name="businessunit",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="businessunit",
            name="head",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="headed_business_units",
                to="employees.employee",
            ),
        ),
        migrations.AddField(
            model_name="businessunit",
            name="legal_entity",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="business_units",
                to="employees.legalentity",
            ),
        ),
        migrations.AddField(
            model_name="businessunit",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="children",
                to="employees.businessunit",
            ),
        ),
        migrations.AddField(
            model_name="costcenter",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="costcenter",
            name="legal_entity",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cost_centers",
                to="employees.legalentity",
            ),
        ),
        migrations.AddField(
            model_name="costcenter",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="owned_cost_centers",
                to="employees.employee",
            ),
        ),
        migrations.AddField(
            model_name="department",
            name="business_unit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="departments",
                to="employees.businessunit",
            ),
        ),
        migrations.AddField(
            model_name="department",
            name="code",
            field=models.CharField(blank=True, db_index=True, default="", max_length=30),
        ),
        migrations.AddField(
            model_name="department",
            name="cost_center",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="departments",
                to="employees.costcenter",
            ),
        ),
        migrations.AddField(
            model_name="department",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="department",
            name="head",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="headed_departments",
                to="employees.employee",
            ),
        ),
        migrations.AddField(
            model_name="designation",
            name="code",
            field=models.CharField(blank=True, db_index=True, default="", max_length=30),
        ),
        migrations.AddField(
            model_name="designation",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="grade",
            name="code",
            field=models.CharField(blank=True, db_index=True, default="", max_length=30),
        ),
        migrations.AddField(
            model_name="grade",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="grade",
            name="level",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="grades",
                to="employees.level",
            ),
        ),
        migrations.AddField(
            model_name="jobfamily",
            name="code",
            field=models.CharField(blank=True, db_index=True, default="", max_length=30),
        ),
        migrations.AddField(
            model_name="jobfamily",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="jobfamily",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="children",
                to="employees.jobfamily",
            ),
        ),
        migrations.AddField(
            model_name="legalentity",
            name="code",
            field=models.CharField(blank=True, db_index=True, default="", max_length=30),
        ),
        migrations.AddField(
            model_name="legalentity",
            name="country",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="legalentity",
            name="currency",
            field=models.CharField(default="INR", max_length=10),
        ),
        migrations.AddField(
            model_name="legalentity",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="legalentity",
            name="logo",
            field=models.URLField(blank=True, default="", max_length=500),
        ),
        migrations.AddField(
            model_name="legalentity",
            name="registered_address",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="employees.location",
            ),
        ),
        migrations.AddField(
            model_name="level",
            name="code",
            field=models.CharField(blank=True, db_index=True, default="", max_length=30),
        ),
        migrations.AddField(
            model_name="level",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="level",
            name="job_family",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="levels",
                to="employees.jobfamily",
            ),
        ),
        migrations.AddField(
            model_name="level",
            name="rank",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="location",
            name="address_line1",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="location",
            name="address_line2",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="location",
            name="city",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="location",
            name="code",
            field=models.CharField(blank=True, db_index=True, default="", max_length=30),
        ),
        migrations.AddField(
            model_name="location",
            name="country",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="location",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="location",
            name="latitude",
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name="location",
            name="longitude",
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name="location",
            name="postal_code",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AddField(
            model_name="location",
            name="state",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="location",
            name="timezone",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AddField(
            model_name="location",
            name="type",
            field=models.CharField(
                choices=[("hq", "Headquarters"), ("branch", "Branch"), ("remote", "Remote")],
                default="branch",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="team",
            name="code",
            field=models.CharField(blank=True, db_index=True, default="", max_length=30),
        ),
        migrations.AddField(
            model_name="team",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="costcenter",
            name="code",
            field=models.CharField(blank=True, db_index=True, default="", max_length=30),
        ),
    ]
