# Generated by Django 6.0.5 on 2026-09-29 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0015_backfill_codes"),
    ]

    operations = [
        migrations.CreateModel(
            name="PayGrade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=150, unique=True)),
                ("code", models.CharField(blank=True, db_index=True, default="", max_length=30)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "min_pay",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
                ),
                (
                    "mid_pay",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
                ),
                (
                    "max_pay",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
                ),
                ("currency", models.CharField(default="INR", max_length=10)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="costcenter",
            name="email_alias",
            field=models.CharField(blank=True, default="", max_length=150),
        ),
        migrations.AddField(
            model_name="department",
            name="email_alias",
            field=models.CharField(blank=True, default="", max_length=150),
        ),
        migrations.AddField(
            model_name="legalentity",
            name="address_line1",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="legalentity",
            name="address_line2",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="legalentity",
            name="city",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="legalentity",
            name="company_identification_number",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AddField(
            model_name="legalentity",
            name="date_of_incorporation",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="legalentity",
            name="financial_year",
            field=models.CharField(
                blank=True,
                choices=[
                    ("april_march", "April - March"),
                    ("january_december", "January - December"),
                    ("july_june", "July - June"),
                ],
                default="",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="legalentity",
            name="legal_name",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="legalentity",
            name="nature_of_business",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="legalentity",
            name="sector",
            field=models.CharField(
                blank=True,
                choices=[
                    ("professionals", "Professionals"),
                    ("manufacturing", "Manufacturing Industry"),
                    ("it_software", "IT & Software"),
                    ("services", "Services"),
                    ("finance", "Finance"),
                    ("other", "Other"),
                ],
                default="",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="legalentity",
            name="state",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="legalentity",
            name="type_of_business",
            field=models.CharField(
                blank=True,
                choices=[
                    ("limited_liability", "Limited Liability"),
                    ("private_limited", "Private Limited"),
                    ("public_limited", "Public Limited"),
                    ("llp", "LLP"),
                    ("partnership", "Partnership"),
                    ("sole_proprietorship", "Sole Proprietorship"),
                ],
                default="",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="legalentity",
            name="zip_code",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AddField(
            model_name="location",
            name="email_alias",
            field=models.CharField(blank=True, default="", max_length=150),
        ),
        migrations.AddField(
            model_name="location",
            name="location_head",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="headed_locations",
                to="employees.employee",
            ),
        ),
        migrations.CreateModel(
            name="AuthorizedSignatory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("designation", models.CharField(blank=True, default="", max_length=150)),
                ("email", models.EmailField(blank=True, default="", max_length=254)),
                ("din_or_pan", models.CharField(blank=True, default="", max_length=30)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "legal_entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="authorized_signatories",
                        to="employees.legalentity",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="LegalEntityBankAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("bank_name", models.CharField(max_length=150)),
                ("account_number", models.CharField(max_length=34)),
                ("ifsc_code", models.CharField(max_length=11)),
                ("branch", models.CharField(blank=True, default="", max_length=150)),
                (
                    "account_type",
                    models.CharField(
                        blank=True,
                        choices=[("savings", "Savings"), ("current", "Current")],
                        default="",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "legal_entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bank_accounts",
                        to="employees.legalentity",
                    ),
                ),
            ],
            options={
                "ordering": ["bank_name", "account_number"],
            },
        ),
        migrations.CreateModel(
            name="Band",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=150, unique=True)),
                ("code", models.CharField(blank=True, db_index=True, default="", max_length=30)),
                ("description", models.TextField(blank=True, default="")),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "pay_grade",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bands",
                        to="employees.paygrade",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
