# Generated by Django 6.0.5 on 2026-09-30 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0017_customreport"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="teams",
            field=models.ManyToManyField(blank=True, related_name="members", to="employees.team"),
        ),
    ]
