# Generated by Django 5.1.15 on 2026-10-01 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0020_merge_20260930_1509"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmployeeRosterInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("employment_status", models.CharField(blank=True, default="", max_length=40)),
                ("dotted_line_manager", models.CharField(blank=True, default="", max_length=200)),
                (
                    "reporting_manager_email",
                    models.EmailField(blank=True, default="", max_length=254),
                ),
                ("l2_manager", models.CharField(blank=True, default="", max_length=200)),
                ("worker_type", models.CharField(blank=True, default="", max_length=40)),
                ("time_type", models.CharField(blank=True, default="", max_length=40)),
                ("attendance_number", models.CharField(blank=True, default="", max_length=50)),
                (
                    "attendance_capture_scheme",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "attendance_tracking_policy",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("exit_status", models.CharField(blank=True, default="", max_length=60)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "employee",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roster_info",
                        to="employees.employee",
                    ),
                ),
            ],
        ),
    ]
