"""Import / re-sync employees from a Keka "EE & Reporting" roster export (.xlsx or .csv).

Idempotent: keyed on Employee Number, so re-running updates rather than duplicates.
The roster has no per-employee email, so a new login is ``<code>@consult-4at.com``
(existing employees keep whatever email they already have). Reporting managers are
linked by name, with the roster's "Reporting Manager Email" used only to recognise
a manager (never as the employee's own email).
"""

import csv
import re
from datetime import date, datetime
from pathlib import Path

import openpyxl
from django.core.management.base import BaseCommand, CommandError
from django.db import transaction

from accounts.models import User
from employees.models import Department, Employee, EmployeeRosterInfo, JobTitle, Location

HEADER_ROW = 3  # xlsx: title rows above, headers on row 3


def _s(value):
    return " ".join(str(value).split()) if value not in (None, "") else ""


def _norm(name):
    return re.sub(r"[^a-z ]", "", _s(name).lower())


def _date(value):
    if isinstance(value, datetime):
        return value.date()
    if isinstance(value, date):
        return value
    text = _s(value)
    for fmt in ("%d-%b-%Y", "%Y-%m-%d", "%d/%m/%Y"):
        try:
            return datetime.strptime(text, fmt).date()
        except ValueError:
            pass
    return None


class Command(BaseCommand):
    help = "Import employees from a Keka roster export (xlsx/csv). Safe to re-run."

    def add_arguments(self, parser):
        parser.add_argument("roster_file", type=str)

    def _read(self, path):
        if path.suffix.lower() == ".xlsx":
            ws = openpyxl.load_workbook(path, data_only=True).active
            headers = [c.value for c in ws[HEADER_ROW]]
            raw = (dict(zip(headers, r)) for r in ws.iter_rows(min_row=HEADER_ROW + 1, values_only=True))
        else:
            with open(path, newline="", encoding="utf-8-sig") as fh:
                raw = list(csv.DictReader(fh))
        # Drops blank spacer rows and the "Generated by Keka" footer.
        return [r for r in raw if _s(r.get("Employee Number")) and _s(r.get("First Name"))]

    @transaction.atomic
    def handle(self, *args, **options):
        path = Path(options["roster_file"])
        if not path.exists():
            raise CommandError(f"File not found: {path}")
        rows = self._read(path)

        created = updated = 0
        by_code = {}
        for row in rows:
            code = _s(row["Employee Number"])
            first, last = _s(row.get("First Name")), _s(row.get("Last Name"))
            employee = Employee.objects.select_related("user").filter(employee_code=code).first()
            if employee:
                user = employee.user
            else:
                email = f"{code.lower()}@consult-4at.com"
                user, _ = User.objects.get_or_create(
                    email=email,
                    defaults={"username": email, "first_name": first, "last_name": last},
                )
            if user.first_name != first or user.last_name != last:
                user.first_name, user.last_name = first, last
                user.save(update_fields=["first_name", "last_name"])

            dept_name, sub_name = _s(row.get("Department")), _s(row.get("Sub Department"))
            department = None
            if dept_name:
                parent, _ = Department.objects.get_or_create(name=dept_name)
                department = parent
                if sub_name and sub_name != dept_name:
                    department, made = Department.objects.get_or_create(
                        name=sub_name, defaults={"parent": parent}
                    )
            title_name = _s(row.get("Job Title"))
            title = JobTitle.objects.get_or_create(name=title_name)[0] if title_name else None
            loc_name = _s(row.get("Location"))
            location = Location.objects.get_or_create(name=loc_name)[0] if loc_name else None

            defaults = {
                "user": user,
                "first_name": first,
                "last_name": last,
                "status": "active" if _s(row.get("Employment Status")) == "Working" else "exited",
                "employment_type": "contract" if _s(row.get("Worker Type")) == "Contingent" else "full_time",
                "date_of_joining": _date(row.get("Date Joined")),
            }
            # Don't blank an assignment HR already made if the roster cell is empty.
            for field, value in (("department", department), ("designation", title), ("location", location)):
                if value is not None:
                    defaults[field] = value
            employee, was_created = Employee.objects.update_or_create(employee_code=code, defaults=defaults)
            EmployeeRosterInfo.objects.update_or_create(
                employee=employee,
                defaults={
                    "employment_status": _s(row.get("Employment Status")),
                    "dotted_line_manager": _s(row.get("Dotted Line Manager")),
                    "reporting_manager_email": _s(row.get("Reporting Manager Email")).lower(),
                    "l2_manager": _s(row.get("L2 Manager")),
                    "worker_type": _s(row.get("Worker Type")),
                    "time_type": _s(row.get("Time Type")),
                    "attendance_number": _s(row.get("Attendance Number")),
                    "attendance_capture_scheme": _s(row.get("Attendance Capture Scheme")),
                    "attendance_tracking_policy": _s(row.get("Attendance Tracking Policy")),
                    "exit_status": _s(row.get("Exit Status")),
                },
            )
            created += was_created
            updated += not was_created
            by_code[code] = employee

        # Name → employee, preferring active people, for manager linking.
        everyone = list(Employee.objects.select_related("user"))
        everyone.sort(key=lambda e: e.status != "active")

        def find_manager(name):
            """Exact normalised match, else all words of the shorter name contained in the longer."""
            target = set(_norm(name).split())
            if not target:
                return None
            for e in everyone:
                if set(_norm(e.full_name).split()) == target:
                    return e
            for e in everyone:
                have = set(_norm(e.full_name).split())
                if have and (have <= target or target <= have) and len(have & target) >= 2:
                    return e
            return None

        linked = unresolved = 0
        for row in rows:
            name = _s(row.get("Reporting Manager"))
            if not name:
                continue
            employee = by_code[_s(row["Employee Number"])]
            manager = find_manager(name)
            if manager and manager.pk != employee.pk:
                if employee.manager_id != manager.pk:
                    employee.manager = manager
                    employee.save(update_fields=["manager", "updated_at"])
                linked += 1
            else:
                unresolved += 1
                self.stdout.write(self.style.WARNING(f"No manager match for {employee.employee_code}: {name!r}"))

        self.stdout.write(
            self.style.SUCCESS(
                f"Roster sync complete: {created} created, {updated} updated, "
                f"{linked} manager links, {unresolved} unresolved."
            )
        )
